In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv('play_tennis.csv')
df.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
df['play'].replace({'Yes':1,'No':0},inplace=True)

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
ohe=OneHotEncoder(sparse=False)
outlook_one_hoe_encoder=ohe.fit_transform(df[['outlook']])

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
oe_temp=OrdinalEncoder(categories=[['Cool','Mild','Hot']],dtype=np.int32)
temp_ordinal=oe_temp.fit_transform(df[['temp']])

In [8]:
oe_humidity=OrdinalEncoder(categories=[['Normal','High']],dtype=np.int32)
humidity_ordinal=oe_humidity.fit_transform(df[['humidity']])

In [9]:
oe_wind=OrdinalEncoder(categories=[['Weak','Strong']],dtype=np.int32)
wind_ordinal=oe_wind.fit_transform(df[['wind']])

In [10]:
df['temp'] = temp_ordinal

In [11]:
df['humidity'] = humidity_ordinal

In [12]:
df['wind'] = wind_ordinal

In [13]:
df['outlook'] = outlook_one_hoe_encoder

In [14]:
X = df.drop(columns=['day','play'])
y = df['play']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
##Apply gini
classifier = DecisionTreeClassifier(criterion='gini')

In [19]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
classifier.score(X_test,y_test)

1.0

In [21]:
##Apply entropy
classifier_entropy = DecisionTreeClassifier(criterion='entropy')
classifier_entropy.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [22]:
classifier_entropy.score(X_test,y_test)

1.0

In [23]:
df.head()

day  outlook  temp  humidity  wind  play
0  D1      0.0     2         1     0     0
1  D2      0.0     2         1     1     0
2  D3      1.0     2         1     0     1
3  D4      0.0     1         1     0     1
4  D5      0.0     0         0     0     1

In [29]:
pre = [0.0,2,1,0]

In [30]:
pre1 = np.array([pre])
pre1

array([[0., 2., 1., 0.]])

In [31]:
classifier.predict(pre1)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [32]:
pred = classifier.predict(pre1)
pred

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [33]:
if pred[0] == 1:
  print('Yes Play Tannis')
else:
  print('Not Play Tannis')

Not Play Tannis
